name: Deploy to Server
on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Pulling latest commits..."
            cd ${{ secrets.SERVER_PATH }}
            git pull origin main

            echo "Ensuring neo4j is running..."
            docker compose up -d --wait neo4j

            echo "Building and deploying app..."
            docker compose up -d --build --no-deps --wait app

            echo "Cleaning up old images..."
            docker image prune -f

            echo "Container status:"
            docker compose ps --format "table {{.Service}}\t{{.Status}}\t{{.Ports}}"

            echo "Deployment complete!"


